/*
Greer Goodman
Caleb Mann
Cody Light
Christopher Taylor
*/
DROP TABLE BOOKING CASCADE CONSTRAINTS;
DROP TABLE ADDRESS CASCADE CONSTRAINTS;
DROP TABLE PHOTOGRAPHER CASCADE CONSTRAINTS;
DROP TABLE PHOTOGRAPH CASCADE CONSTRAINTS;
DROP TABLE PACKAGE_ORDER CASCADE CONSTRAINTS;
DROP TABLE CLIENT CASCADE CONSTRAINTS;
DROP TABLE CONTRACT CASCADE CONSTRAINTS;
DROP TABLE PAYMENT CASCADE CONSTRAINTS;

CREATE TABLE BOOKING(
    EVENT_ID NUMBER(30,0) PRIMARY KEY,
    EVENT_TYPE VARCHAR2(20),
    DESCRIPTION VARCHAR(100),
    BOOKING_DATE VARCHAR2(10),
    BOOKING_TIME VARCHAR2(10)
);
CREATE TABLE ADDRESS(
  ADDRESS_ID NUMBER(30,0) PRIMARY KEY,
  Street VARCHAR2(50),
  CITY VARCHAR2(25),
  STATE VARCHAR2(2),
  ZIP_CODE VARCHAR2(10)
);
CREATE TABLE PHOTOGRAPHER(
    STAFF_ID NUMBER(30,0)PRIMARY KEY,
    TITLE VARCHAR(50),
    EVENT_ID NUMBER(30,0),
    STAFF_NAME VARCHAR2(40),
    ADDRESS_ID NUMBER(30,0),
    TIMEAVAILABLE VARCHAR2(30),
    FOREIGN KEY(EVENT_ID)REFERENCES BOOKING(EVENT_ID),
    FOREIGN KEY(ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID)
);
CREATE TABLE PHOTOGRAPH(
    PHOTO_ID NUMBER(30,0) PRIMARY KEY,
    STAFF_ID NUMBER(30,0),
    PHOTO_DATE VARCHAR2(30),
    FEE VARCHAR2(20),
    PHOTO_SIZE VARCHAR2(15),
    FILENAME VARCHAR2(40),
    FOREIGN KEY(STAFF_ID) REFERENCES PHOTOGRAPHER(STAFF_ID)
);
CREATE TABLE PACKAGE_ORDER(
    ORDER_ID NUMBER(30,0) PRIMARY KEY,
    PHOTO_ID NUMBER(30,0),
    PACKAGE_NAME VARCHAR2(50),
    PACKAGE_PRICE VARCHAR2(30),
    QUANTITY NUMBER(30,0),
    FOREIGN KEY(PHOTO_ID)REFERENCES PHOTOGRAPH(PHOTO_ID)
);
CREATE TABLE CLIENT(
    CLIENT_ID NUMBER(30,0) PRIMARY KEY,
    ORDER_ID NUMBER(30,0),
    CLIENT_NAME VARCHAR2(40),
    CLIENT_EMAIL VARCHAR2(40),
    ADDRESS_ID NUMBER(30,0),
    FOREIGN KEY(ORDER_ID) REFERENCES PACKAGE_ORDER(ORDER_ID),
    FOREIGN KEY(ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID)
);
CREATE TABLE CONTRACT(
    Contract_ID NUMBER(30,0) PRIMARY KEY,
    Event_ID NUMBER (30,0),
    Client_ID NUMBER (30,0),
    Location VARCHAR2(30),
    Service_Date VARCHAR(20),
    Service_Time VARCHAR2(20),
    Photographer_ID NUMBER(30,0),
    DEPOSIT NUMBER(10,0),
    FOREIGN KEY(EVENT_ID) REFERENCES BOOKING(EVENT_ID),
    FOREIGN KEY(CLIENT_ID) REFERENCES CLIENT(CLIENT_ID),
    FOREIGN KEY(PHOTOGRAPHER_ID) REFERENCES PHOTOGRAPHER(STAFF_ID)
);
CREATE TABLE PAYMENT(
    PAYMENT_ID NUMBER(30,0) PRIMARY KEY,
    CLIENT_ID NUMBER(30,0),
    ORDER_ID NUMBER(30,0),
    RECEIVED_DATE VARCHAR2(20),
    DUE_DATE VARCHAR2(20),
    AMOUNT NUMBER(10,0),
    FOREIGN KEY(CLIENT_ID) REFERENCES CLIENT(CLIENT_ID),
    FOREIGN KEY(ORDER_ID) REFERENCES PACKAGE_ORDER(ORDER_ID)
);